- hosts: vcenter
  collections:
    - ansible.posix
  tasks:
      - name: Inject the local user's pubkey
        authorized_key:
          user: root
          state: present
          key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
